### ISSUE TITLE
issues for importing `RLQP`

### ISSUE THREAD

**Issue by Junyoungpark** [BerkeleyAutomation/rlqp#1]
Hi, 

Thank you for sharing this excellent work!
While I tried to run the code by following the guide written in the readme, I encountered an import error.

```python
from rlqp import RLQP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RLQP' from 'rlqp' (/home/silab9/anaconda3/envs/torch190/lib/python3.8/site-packages/rlqp/__init__.py)
```
I guess the `rlqp` library undergoes some API change. Thus, the import procedure doesn't work as intended. Can you help me to fix this issue?

BTW it seems like `rlqp` itself looks almost the same as `osqp-python`. Do you have any specific reason not to directly use `osqp-python` rather than developing `rlqp`? When I skim through the code inside `rlqp-pyhon` everything should work fine if we change the use of `RLQP` to the `OSQP` class of `osqp`.

**Comment by parasj** [comment]
Apologies for the delay in reply! We didn't see the notifications on this old repo. Please email me (see profile) if you are still interested in the project.
